#!/bin/bash

# SSH SCREEN MANAGER v0.1a
### CONFIGURATION ########
##############################################
## prefix for generated screens
SCREEN_NAME="util_0"
## command to run upon each screen generation
COMMAND="ssh handyman@util_0"
##############################################

unused_count=0;
first_unused() {
   # echo Checking if $SCREEN_NAME-$unused_count exists...
   if  screen -list | grep -q "$SCREEN_NAME-$unused_count"; then
      let "unused_count++"
      first_unused
   fi
}

first_unused
echo Creating screen $SCREEN_NAME-$unused_count...
sleep 1
if [ "$1" = "-d" ]; then
	screen -dmS $SCREEN_NAME-$unused_count $COMMAND
else
	screen -S $SCREEN_NAME-$unused_count $COMMAND
fi
